version: "3.8"
services:
  database_server:
    image: mongo
    container_name: ${DATABASE_SERVER_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${DATABASE_SERVER_PORT}:${DATABASE_SERVER_PORT}"
    env_file: ./database/.env
    networks:
      - backend
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  database_client:
    image: mongo-express
    container_name: ${DATABASE_CLIENT_CONTAINER_NAME}
    env_file: ./databaseclient/.env
    links:
      - database_server
    restart: unless-stopped
    ports:
      - "${DATABASE_CLIENT_PORT}:${DATABASE_CLIENT_PORT}"
    networks:
      - backend

  server:
    depends_on:
      - database_server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${SERVER_DOCKER_PORT}:${SERVER_LOCAL_PORT}
    env_file: ./server/.env
    networks:
      - backend
  
  reverse_proxy:
    image: nginx
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./reverse_proxy/key.pem:/root/ssl/key.pem
      - ./reverse_proxy/cert.pem:/root/ssl/cert.pem
    ports:
      - ${REVERSE_PROXY_PORT}:${REVERSE_PROXY_PORT}
    depends_on:
      - server

networks:
  backend:
